[package]
name = "hashgraph"
version = "0.1.0"
authors = ["Jay Butera <buterajay@gmail.com>"]

[dependencies]
futures = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
names = "0.11"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
